name: testk8s

on: 
  push: 
     branches: 
      - main
      - master
  workflow_dispatch:
jobs:
  setupk8s:
    runs-on: ubuntu-latest
    steps:
      - name: setting up minikube
        uses: manusa/actions-setup-minikube@v2.4.2
        with:
          minikube version: 'v1.16.0'
          kubernetes version: 'v1.19.2'
      - name: Start meshery server using mesheryctl
        run: |
           curl -L https://git.io/meshery | PLATFORM=kubernetes bash -
           sleep 100s
      - name: Try to see if meshery is up
        run: kubectl get pods -n meshery
