name: testk8s

on: 
  push: 
     branches: 
      - main
      - master
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setting up minikube
        uses: manusa/actions-setup-minikube@v2.4.2
        with:
          minikube version: 'v1.16.0'
          kubernetes version: 'v1.19.2'
          driver: docker
      # - name: setenv
      #   run: minikube docker-env
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.REVOLY_DOCKER_PASSWORD }} | docker login -u ${{ secrets.REVOLY_DOCKER_USERNAME }} --password-stdin
      # - name: Get the version
      #   id: vars
      #   run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      # - name: Build the tagged Docker image
      #   run: docker build . --file Dockerfile --tag revoly/testistio:test
      # - name: push to local
      #   run: docker push revoly/testistio:test
      
      - name: setup meshery config 
        env:
          provider_token: ${{ secrets.PROVIDER_TOKEN }}
        run:  echo $provider_token ;chmod +x ./mesheryconf.sh ;./mesheryconf.sh
        
      - name: Start meshery server using mesheryctl
        run: |
           curl -L https://git.io/meshery | PLATFORM=kubernetes bash -
           sleep 100s
      - name: Try to see if meshery is up
        run: kubectl get pods -n meshery
      - name: start adapter
        run: |
          kubectl apply -f ./.github/meshery-istio-deployment.yaml --namespace=meshery
          kubectl apply -f ./.github/meshery-istio-service.yaml --namespace=meshery
          kubectl apply -f ./.github/service-account.yaml --namespace=meshery
      - name: start tunelling
        run: minikube tunnel &> /dev/null &
      - name: wait 20 sec
        run: sleep 20s
      - name: check if pods started
        run: |
          podName=$(kubectl get pods -o wide -n meshery | sed -n 2p | tr -s ' ' | cut -d " " -f 1)
          kubectl logs pod/$podName -n meshery






      # - name: reset meshery addr
      #   run: |
      #     kubectl get svc -n meshery 
      #     svcip="http://$(kubectl get svc -n meshery | grep "meshery " | tr -s ' ' | cut -d " " -f 3):9081"
      #     echo "this is $svcip"
      #     config='{"contexts":{"local":{"endpoint":'$svcip',"token":"Default","platform":"kubernetes","adapters":[],"channel":"stable","version":"latest"}},"current-context":"local","tokens":[{"location":"auth.json","name":"Default"}]}'
      #     echo $config  > ~/.meshery/config.yaml
      #     cat  ~/.meshery/config.yaml
      - name: port forward
        run: kubectl port-forward service/meshery 9081:9081 -n meshery& > /dev/null
      - name: check status
        run: mesheryctl system status
      - name: change config
        run: |
         config='{"contexts":{"local":{"endpoint":"http://localhost:9081","token":"Default","platform":"kubernetes","adapters":[],"channel":"stable","version":"latest"}},"current-context":"local","tokens":[{"location":"auth.json","name":"Default"}]}'
         echo $config > ~/.meshery/config.yaml
      - name: pattern list 
        run: mesheryctl pattern list
      - name: pattern apply
        run: mesheryctl pattern apply -f ./.github/test.yaml 
      - name: check adapter logs
        run: |
            podname=$(kubectl get pods -n meshery | grep istio | tr -s ' ' | cut -d " " -f 1)
            kubectl describe  pod $podname -n meshery
      - name: check meshery logs
        run: |
          podName=$(kubectl get pods -o wide -n meshery | sed -n 2p | tr -s ' ' | cut -d " " -f 1)
          kubectl logs pod/$podName -n meshery

      # - name: Setup Go
      #   uses: actions/setup-go@v2
      #   with:
      #     go-version: 1.16.x
      # - name: start adapter
      #   run: DEBUG=true MESHERY_SERVER=$ENDPOINT:9081 go run main.go &
      # - name: Install service mesh
      #   run: mesheryctl mesh deploy --adapter meshery-istio --namespace istio-system
      # - name: sleep
      #   run: 100s
      # - name: Check
      #   run: kubectl get pods -n istio-system
      # - name: get the routes
      #   run: ip route

