name: Test Istio Adapter

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
  pull_request:
    branches:
      - master
jobs:
  TestIstio:
    uses: Revolyssup/test-workflows/.github/workflows/general.yaml@main
    with:
      expected_pods: istio-egressgateway,istio-ingressgateway,istiod
      expected_pods_namespaces: istio-system,istio-system,istio-system
      deployment_url: https://raw.githubusercontent.com/meshery/meshery/master/install/deployment_yamls/k8s/meshery-istio-deployment.yaml
      service_url: https://raw.githubusercontent.com/meshery/meshery/master/install/deployment_yamls/k8s/meshery-istio-service.yaml
      adapter_name: istio
      patternfile: "name: IstioSM
        version: 1.0.1
        services:
          istio:
            type: IstioMesh
            namespace: istio-system
            settings:
              version: 1.9.1"
    secrets:
      token: ${{ secrets.PROVIDER_TOKEN }}