name: testk8s

on: 
  push: 
     branches: 
      - main
      - master
  workflow_dispatch:
jobs:
  test:
    env:
      ENDPOINT: ""
    runs-on: ubuntu-latest
    steps:
      - name: setting up minikube
        uses: manusa/actions-setup-minikube@v2.4.2
        with:
          minikube version: 'v1.16.0'
          kubernetes version: 'v1.19.2'
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: setup meshery config 
        run:  chmod +x ./mesheryconf.sh ;./mesheryconf.sh
        
      - name: Start meshery server using mesheryctl
        run: |
           curl -L https://git.io/meshery | PLATFORM=kubernetes bash -
           sleep 100s
      - name: Try to see if meshery is up
        run: kubectl get pods -n meshery
      - name: start tunelling
        run: minikube tunnel & 
      - name: wait 10 sec
        run: sleep 10s
      - name: Get meshery endpoint 
        run: export ENDPOINT=kubectl get svc -n meshery | grep -w "meshery " |  tr -s ' ' | cut -d " " -f 3 
      - name: echo endpoint
        run: echo $ENDPOINT
      - name: Tryna curl
        run: curl http://$ENDPOINT:9081/api/oam/workload
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ‘1.16.0’
      - name: start adapter
        run: DEBUG=true MESHERY_SERVER=$ENDPOINT:9081 go run main.go
